[package]
name = "pinset_sync_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork="0.1.20"
json="0.12.4"
