debug = true

[api]
host="0.0.0.0"
port=8889
worker=2

[proxy]
host="127.0.0.1"
ipfs_port=5001
ipfs_cluster_port=9094
timeout=30
timeout_pin=300
timeout_allocations=600
timeout_pin_ls=300
worker=8
wait_alive_retry=6

[consul]
host="127.0.0.1"
port=8500

[db]
path="db"

